# Generated by Django 2.1.4 on 2018-12-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
